In [6]:
import pandas as pd
import numpy as np 
data = pd.read_csv("part-00000.csv")

In [7]:
def is_numeric(value):
    return isinstance(value, (int, float, np.number))

numeric_check = df.applymap(is_numeric)

In [10]:
numeric_check = data.applymap(is_numeric)

In [11]:
numeric_check

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_GEO_CD,BENE_AGE_LVL,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_EVER_MA_CNT,EVER_MA_PRTCPTN_RATE,BENE_AVG_AGE,...,BENE_RACE_HSPNC_PCT,BENE_RACE_OTHR_PCT,BENE_DUAL_PCT,BENE_AVG_RISK_SCRE,TOT_MDCR_PYMT_AMT,TOT_MDCR_STDZD_PYMT_AMT,TOT_MDCR_STDZD_RA_PYMT_AMT,TOT_MDCR_PYMT_PC,TOT_MDCR_STDZD_PYMT_PC,TOT_MDCR_STDZD_RA_PYMT_PC
0,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50345,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50346,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50347,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50348,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50349,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
for col in data.applymap(is_numeric).columns:
    print(col, data[col])

YEAR 0        2007
1        2007
2        2007
3        2007
4        2007
         ...
50345    2021
50346    2021
50347    2021
50348    2021
50349    2021
Name: YEAR, Length: 50350, dtype: int64
BENE_GEO_LVL 0        National
1        National
2        National
3           State
4           State
           ...
50345      County
50346      County
50347      County
50348      County
50349      County
Name: BENE_GEO_LVL, Length: 50350, dtype: object
BENE_GEO_DESC 0           National
1           National
2           National
3                 AK
4                 AK
            ...
50345       WY-Teton
50346     WY-UNKNOWN
50347       WY-Uinta
50348    WY-Washakie
50349      WY-Weston
Name: BENE_GEO_DESC, Length: 50350, dtype: object
BENE_GEO_CD 0            NaN
1            NaN
2            NaN
3            2.0
4            2.0
          ...
50345    56039.0
50346    56999.0
50347    56041.0
50348    56043.0
50349    56045.0
Name: BENE_GEO_CD, Length: 50350, dtype: float64
BENE_AGE_LVL 0        All
1        <65
2        >65
3        All
4        <65
        ...
50345    All
50346    All
50347    All
50348    All
50349    All
Name: BENE_AGE_LVL, Length: 50350, dtype: object
BENES_WTH_PTAPTB_CNT 0        42286251
1         6560776
2        35725475
3           53634
4            9791
           ...
50345        3657
50346           *
50347        3573
50348        1926
50349        1648
Name: BENES_WTH_PTAPTB_CNT, Length: 50350, dtype: object
BENES_FFS_CNT 0        32872694
1         5509342
2        27363352
3           53203
4            9729
           ...
50345        3388
50346           *
50347        2971
50348        1876
50349        1484
Name: BENES_FFS_CNT, Length: 50350, dtype: object
BENES_EVER_MA_CNT 0        9413557
1        1051434
2        8362123
3            431
4             62
          ...
50345        269
50346          *
50347        602
50348         50
50349        164
Name: BENES_EVER_MA_CNT, Length: 50350, dtype: object
EVER_MA_PRTCPTN_RATE 0        0.2226
1        0.1603
2        0.2341
3         0.008
4        0.0063
          ...
50345    0.0736
50346         *
50347    0.1685
50348     0.026
50349    0.0995
Name: EVER_MA_PRTCPTN_RATE, Length: 50350, dtype: object
BENE_AVG_AGE 0        72
1        50
2        76
3        70
4        50
         ..
50345    73
50346     *
50347    70
50348    73
50349    73
Name: BENE_AVG_AGE, Length: 50350, dtype: object
BENE_FEML_PCT 0        0.5615
1        0.4686
2        0.5802
3        0.5093
4        0.4592
          ...
50345    0.4991
50346         *
50347    0.4968
50348    0.5144
50349    0.5027
Name: BENE_FEML_PCT, Length: 50350, dtype: object
BENE_MALE_PCT 0        0.4385
1        0.5314
2        0.4198
3        0.4907
4        0.5408
          ...
50345    0.5009
50346         *
50347    0.5032
50348    0.4856
50349    0.4973
Name: BENE_MALE_PCT, Length: 50350, dtype: object
BENE_RACE_WHT_PCT 0        0.8199
1        0.6854
2         0.847
3        0.7465
4        0.6568
          ...
50345         *
50346         *
50347         *
50348         *
50349    0.9616
Name: BENE_RACE_WHT_PCT, Length: 50350, dtype: object
BENE_RACE_BLACK_PCT 0        0.0938
1        0.1949
2        0.0735
3        0.0273
4        0.0544
          ...
50345         *
50346         *
50347         *
50348         *
50349         0
Name: BENE_RACE_BLACK_PCT, Length: 50350, dtype: object
BENE_RACE_HSPNC_PCT 0         0.055
1        0.0847
2         0.049
3        0.0205
4        0.0304
          ...
50345         *
50346         *
50347         *
50348         *
50349    0.0101
Name: BENE_RACE_HSPNC_PCT, Length: 50350, dtype: object
BENE_RACE_OTHR_PCT 0        0.0313
1         0.035
2        0.0305
3        0.2057
4        0.2584
          ...
50345         *
50346         *
50347         *
50348         *
50349    0.0283
Name: BENE_RACE_OTHR_PCT, Length: 50350, dtype: object
BENE_DUAL_PCT 0        0.2076
1        0.5278
2        0.1432
3        0.2492
4        0.6075
          ...
50345    0.0319
50346         *
50347    0.1279
50348    0.1269
50349    0.0964
Name: BENE_DUAL_PCT, Length: 50350, dtype: object
BENE_AVG_RISK_SCRE 0           1
1        1.08
2        0.98
3        0.85
4        0.97
         ...
50345    0.63
50346       *
50347    0.82
50348     0.8
50349    0.77
Name: BENE_AVG_RISK_SCRE, Length: 50350, dtype: object
TOT_MDCR_PYMT_AMT 0        274697746090.98
1         46967991045.91
2        227729755045.07
3           370332472.46
4            74239513.86
              ...
50345        28895251.89
50346                  *
50347        30910529.81
50348        21218839.49
50349         15699110.9
Name: TOT_MDCR_PYMT_AMT, Length: 50350, dtype: object
TOT_MDCR_STDZD_PYMT_AMT 0        264086258659.14
1         45115487119.64
2        218970771539.44
3           295318808.76
4            59434246.51
              ...
50345        24741616.83
50346                  *
50347        27346643.44
50348        18840571.97
50349        13987602.77
Name: TOT_MDCR_STDZD_PYMT_AMT, Length: 50350, dtype: object
TOT_MDCR_STDZD_RA_PYMT_AMT 0        273783850649.77
1         43150812364.53
2        230633038285.28
3           355469816.38
4             61569110.9
              ...
50345        41116517.79
50346                  *
50347        35686806.61
50348         24683165.1
50349        18485716.51
Name: TOT_MDCR_STDZD_RA_PYMT_AMT, Length: 50350, dtype: object
TOT_MDCR_PYMT_PC 0         8356.41
1         8525.15
2         8322.44
3         6960.74
4         7630.74
           ...
50345      8528.7
50346           *
50347    10404.08
50348    11310.68
50349    10578.92
Name: TOT_MDCR_PYMT_PC, Length: 50350, dtype: object
TOT_MDCR_STDZD_PYMT_PC 0         8033.61
1         8188.91
2         8002.34
3         5550.79
4         6108.98
           ...
50345     7302.72
50346           *
50347     9204.52
50348    10042.95
50349     9425.61
Name: TOT_MDCR_STDZD_PYMT_PC, Length: 50350, dtype: object
TOT_MDCR_STDZD_RA_PYMT_PC 0         8328.61
1          7832.3
2         8428.54
3         6681.39
4         6328.41
           ...
50345    12135.93
50346           *
50347    12011.72
50348    13157.34
50349    12456.68
Name: TOT_MDCR_STDZD_RA_PYMT_PC, Length: 50350, dtype: object

In [12]:
data

,YEAR,BENE_GEO_LVL,BENE_GEO_DESC,BENE_GEO_CD,BENE_AGE_LVL,BENES_WTH_PTAPTB_CNT,BENES_FFS_CNT,BENES_EVER_MA_CNT,EVER_MA_PRTCPTN_RATE,BENE_AVG_AGE,...,BENE_RACE_HSPNC_PCT,BENE_RACE_OTHR_PCT,BENE_DUAL_PCT,BENE_AVG_RISK_SCRE,TOT_MDCR_PYMT_AMT,TOT_MDCR_STDZD_PYMT_AMT,TOT_MDCR_STDZD_RA_PYMT_AMT,TOT_MDCR_PYMT_PC,TOT_MDCR_STDZD_PYMT_PC,TOT_MDCR_STDZD_RA_PYMT_PC
0,2007,National,National,NaN,All,42286251,32872694,9413557,0.2226,72,...,0.055,0.0313,0.2076,1,274697746090.98,264086258659.14,273783850649.77,8356.41,8033.61,8328.61
1,2007,National,National,NaN,<65,6560776,5509342,1051434,0.1603,50,...,0.0847,0.035,0.5278,1.08,46967991045.91,45115487119.64,43150812364.53,8525.15,8188.91,7832.3
2,2007,National,National,NaN,>65,35725475,27363352,8362123,0.2341,76,...,0.049,0.0305,0.1432,0.98,227729755045.07,218970771539.44,230633038285.28,8322.44,8002.34,8428.54
3,2007,State,AK,2.0,All,53634,53203,431,0.008,70,...,0.0205,0.2057,0.2492,0.85,370332472.46,295318808.76,355469816.38,6960.74,5550.79,6681.39
4,2007,State,AK,2.0,<65,9791,9729,62,0.0063,50,...,0.0304,0.2584,0.6075,0.97,74239513.86,59434246.51,61569110.9,7630.74,6108.98,6328.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50345,2021,County,WY-Teton,56039.0,All,3657,3388,269,0.0736,73,...,*,*,0.0319,0.63,28895251.89,24741616.83,41116517.79,8528.7,7302.72,12135.93
50346,2021,County,WY-UNKNOWN,56999.0,All,*,*,*,*,*,...,*,*,*,*,*,*,*,*,*,*
50347,2021,County,WY-Uinta,56041.0,All,3573,2971,602,0.1685,70,...,*,*,0.1279,0.82,30910529.81,27346643.44,35686806.61,10404.08,9204.52,12011.72
50348,2021,County,WY-Washakie,56043.0,All,1926,1876,50,0.026,73,...,*,*,0.1269,0.8,21218839.49,18840571.97,24683165.1,11310.68,10042.95,13157.34
50349,2021,County,WY-Weston,56045.0,All,1648,1484,164,0.0995,73,...,0.0101,0.0283,0.0964,0.77,15699110.9,13987602.77,18485716.51,10578.92,9425.61,12456.68

In [ ]:
val numericColumnsRDD = columnsRDD.map(columns => {
  val column0 = parseNumeric(columns(0))
  val column1 = columns(1) 
  val column2 = columns(2)
  val column3 = parseNumeric(columns(3))
  val column4 = columns(4)
  val column5 = parseNumeric(columns(5))
  val column6 = parseNumeric(columns(6))
  val column7 = parseNumeric(columns(7))
  val column8 = parseNumeric(columns(8))
  val column9 = parseNumeric(columns(9))
  val column10 = parseNumeric(columns(10))
  val column11 = parseNumeric(columns(11))
  val column12 = parseNumeric(columns(12))
  val column13 = parseNumeric(columns(13))
  val column14= parseNumeric(columns(14))
  val column15= parseNumeric(columns(15))
  val column16= parseNumeric(columns(16))
  val column17 = parseNumeric(columns(17))
  val column18= parseNumeric(columns(18))
  val column19= parseNumeric(columns(19))
  val column20= parseNumeric(columns(20))
  val column21 = parseNumeric(columns(21))
  val column22= parseNumeric(columns(22))
  val column23= parseNumeric(columns(23))
  
  Array(column0, column1, column2,column3,column4,column5,column6,column7,column8,column9,column10,column11,column12,column13,column14,column15,column16,column17,column18,column19,column20,column21,column22,column23)
})